export const STOP_WORDS: Set<string> = new Set([
  "i", "me", "my", "myself", "we", "our", "ours", "ourselves",
  "you", "your", "yours", "yourself", "yourselves",
  "he", "him", "his", "himself", "she", "her", "hers", "herself",
  "it", "its", "itself", "they", "them", "their", "theirs", "themselves",
  "what", "which", "who", "whom", "this", "that", "these", "those",
  "am", "is", "are", "was", "were", "be", "been", "being",
  "have", "has", "had", "having", "do", "does", "did", "doing",
  "a", "an", "the", "and", "but", "if", "or", "because", "as",
  "until", "while", "of", "at", "by", "for", "with", "about",
  "against", "between", "through", "during", "before", "after",
  "above", "below", "to", "from", "up", "down", "in", "out",
  "on", "off", "over", "under", "again", "further", "then", "once",
  "here", "there", "when", "where", "why", "how", "all", "both",
  "each", "few", "more", "most", "other", "some", "such", "no",
  "nor", "not", "only", "own", "same", "so", "than", "too",
  "very", "s", "t", "can", "will", "just", "don", "should", "now",
  "d", "ll", "m", "o", "re", "ve", "y", "ain",
  "aren", "couldn", "didn", "doesn", "hadn", "hasn", "haven",
  "isn", "ma", "mightn", "mustn", "needn", "shan", "shouldn",
  "wasn", "weren", "won", "wouldn",
  "also", "could", "would", "may", "might", "shall", "must",
  "need", "get", "got", "gets", "getting", "go", "goes", "going",
  "gone", "went", "come", "comes", "coming", "came", "make",
  "makes", "making", "made", "take", "takes", "taking", "took",
  "taken", "give", "gives", "giving", "gave", "given", "say",
  "says", "said", "saying", "tell", "tells", "told", "telling",
  "know", "knows", "knew", "known", "knowing", "think", "thinks",
  "thought", "thinking", "see", "sees", "saw", "seen", "seeing",
  "want", "wants", "wanted", "wanting", "use", "uses", "used",
  "using", "find", "finds", "found", "finding",
  "put", "still", "well", "back", "even", "new", "way",
  "like", "much", "really", "right", "thing", "things",
]);
